apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: '9090'
    prometheus.io/scrape: "true"
    sidecar.jaegertracing.io/inject: "true"
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: maur1/backend-v2:latest
        imagePullPolicy: Always
        ports:
        - name: backendport
          containerPort: 8080
        env:
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_AGENT_HOST
          value: "my-jaeger-tracing-agent.default.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend
      port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend
    path: /metrics
    interval: 60s
  namespaceSelector:
    matchNames:
    - default